[package]
name = "slog-error-chain-derive"
description = "derive macros for slogging error cause chains"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"

[features]
nested-values = []
